# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - WebApplication-ScanGhost
        
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Só dispara se houver alteração na API
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' # Verifique se seu projeto usa .NET 8 ou 9

      - name: Restore dependencies
        run: dotnet restore backend/ScanGhost.sln # Aponte para o seu .sln ou .csproj dentro de backend

      - name: Build
        run: dotnet build backend/ScanGhost.sln --configuration Release --no-restore

      - name: Publish
        # O output vai para uma pasta temporária fora do diretório do código
        run: dotnet publish backend/ScanGhost.sln -c Release -o ./publish_output

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: ./publish_output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write # Necessário para o login via OIDC (sem senha)
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-artifact
          path: ./publish_output

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_66E32F74FE5443699D0BAE4D4BE6B28A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_482A09C166224A6DA38F179AE4E8FF65 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FD69E84DB5214C67A09274DABF25461F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WebApplication-ScanGhost'
          slot-name: 'Production'
          package: ./publish_output