name: CI/CD ScanGhost - Full Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
# --- JOB 1: BACKEND (ASP.NET CORE) ---
  build-and-deploy-backend:
    if: contains(github.event.head_commit.message, '[skip backend]') == false
    runs-on: ubuntu-latest
    name: Backend Build & Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore & Build
        # Usamos o caminho da pasta. O dotnet buscará o .sln ou .csproj lá dentro.
        run: |
          dotnet restore backend/
          dotnet build backend/ --configuration Release --no-restore

      - name: Publish
        # Publicamos o projeto apontando para a pasta do backend
        run: dotnet publish backend/ -c Release -o ./publish_api

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_66E32F74FE5443699D0BAE4D4BE6B28A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_482A09C166224A6DA38F179AE4E8FF65 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FD69E84DB5214C67A09274DABF25461F }}

      - name: Deploy API to Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WebApplication-ScanGhost'
          package: ./publish_api

  # --- JOB 2: FRONTEND (AZURE STATIC WEB APPS) ---
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    name: Frontend Build & Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build And Deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_CLIFF_05893530F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### CONFIGURAÇÃO DE PASTAS CORRIGIDA ######
          app_location: "/frontend"      # Pasta em minúsculo conforme seu repo
          api_location: ""               # Deixe vazio pois a API está em outro serviço
          output_location: "dist"        # Geralmente 'dist' ou 'build', verifique seu framework (React/Vue)